function [x,y,telapsed]=generateRandnMarsaPolar(m1,v1,m2,v2,sampleAmount)
%generate two random variables using Marsaglia's polar method
tstart = tic;
i = 0; % the random number generated by the algorithm 
% Geberate X and Y that are N(0,1) random variables and independent
while(i<=sampleAmount)
    u1 = 2*rand()-1;
    u2 = 2*rand()-1;
    s = u1^2 + u2^2;
    if(s < 1)
        i = i + 1;
        X(i) = sqrt(-2*log(s)/s)*u1;
        Y(i) = sqrt(-2*log(s)/s)*u2;
    end
end

% Scale them to a particular mean and variance 
x = sqrt(v1)*X + m1; % x~ N(M1,V1)
y = sqrt(v2)*Y + m2; % y~ N(M2,V2)

telapsed = toc(tstart);